
server:
  port: 8080
  context-path: /springbootdemo
spring:
  thymeleaf:
    cache: false
  freemarker:
    cache: false
    allow-request-override: false
    check-template-location: true
    charset: utf-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
